name: CD

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

env:
  PROJECT_TYPE: KEXT

jobs:
  build:
    name: Build
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          
      - name: Fetch Dependencies 
        run: |
          BUILD_MODE=prebuilt src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1
          git clone https://github.com/acidanthera/VirtualSMC.git
          
      - name: Build All Schemes
        run: |
          xcodebuild -scheme "AMDRyzenCPUPowerManagement" -jobs 1 -arch x86_64 -configuration Release -derivedDataPath ./build
          xcodebuild -scheme "APGLaunchHelper" -jobs 1 -arch x86_64 -configuration Release -derivedDataPath ./build
          xcodebuild -scheme "AMD Power Gadget" -jobs 1 -arch x86_64 -configuration Release -derivedDataPath ./build
          xcodebuild -scheme "SMCAMDProcessor" -jobs 1 -arch x86_64 -configuration Release -derivedDataPath ./build

      - name: Archive Artifacts
        run: |
          rm -rf build/Build/Products/Release/*.dSYM
          rm -rf build/Build/Products/Release/*.swiftmodule
          rm -rf build/Build/Products/Release/APGLaunchHelper*
          zip -r build/Release.zip build/Build/Products/Release
        
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/Release.zip

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/Release.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


